[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds001226_sub-PAT15/fmriprep_wf/single_subject_PAT15_wf/func_preproc_ses_preop_task_rest_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds001226_sub-PAT15/fmriprep_wf/single_subject_PAT15_wf/func_preproc_ses_preop_task_rest_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds001226_sub-PAT15/fmriprep_wf/single_subject_PAT15_wf/func_preproc_ses_preop_task_rest_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds001226_sub-PAT15/fmriprep_wf/single_subject_PAT15_wf/func_preproc_ses_preop_task_rest_wf/unwarp_wf/resample/sourcedata/templateflow 
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
            code = _serve_one(child_r, fds,code = _serve_one(child_r, fds,code = _serve_one(child_r, fds,

    
      File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
code = _serve_one(child_r, fds,  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
code = _serve_one(child_r, fds,  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one


  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
        code = spawn._main(child_r, parent_sentinel)    
code = spawn._main(child_r, parent_sentinel)code = spawn._main(child_r, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main

      File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    code = spawn._main(child_r, parent_sentinel)  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
code = spawn._main(child_r, parent_sentinel)

  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
        prepare(preparation_data)    prepare(preparation_data)
prepare(preparation_data)

  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
      File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
      File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
prepare(preparation_data)prepare(preparation_data)

  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
        _fixup_main_from_path(data['init_main_from_path'])    _fixup_main_from_path(data['init_main_from_path'])

_fixup_main_from_path(data['init_main_from_path'])  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path

      File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
_fixup_main_from_path(data['init_main_from_path'])

  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
            main_content = runpy.run_path(main_path,    main_content = runpy.run_path(main_path,
main_content = runpy.run_path(main_path,
main_content = runpy.run_path(main_path,
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path

  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
    main_content = runpy.run_path(main_path,
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
            return _run_module_code(code, init_globals, run_name,    return _run_module_code(code, init_globals, run_name,
return _run_module_code(code, init_globals, run_name,
return _run_module_code(code, init_globals, run_name,
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code

  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,            _run_code(code, mod_globals, init_globals,
_run_code(code, mod_globals, init_globals,return _run_module_code(code, init_globals, run_name,
_run_code(code, mod_globals, init_globals,


  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)            exec(code, run_globals)
_run_code(code, mod_globals, init_globals,
exec(code, run_globals)exec(code, run_globals)
  File "/opt/conda/bin/fmriprep", line 5, in <module>


  File "/opt/conda/bin/fmriprep", line 5, in <module>
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
  File "/opt/conda/bin/fmriprep", line 5, in <module>
  File "/opt/conda/bin/fmriprep", line 5, in <module>
        from fmriprep.cli.run import main        from fmriprep.cli.run import main
from fmriprep.cli.run import main    from fmriprep.cli.run import main

  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>

  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
  File "/opt/conda/bin/fmriprep", line 5, in <module>
            from fmriprep.cli.run import main    from .. import config    from .. import config
from .. import config
from .. import config

  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>

  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
    from .. import config
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
                from templateflow import __version__ as _tf_verfrom templateflow import __version__ as _tf_verfrom templateflow import __version__ as _tf_ver
from templateflow import __version__ as _tf_ver


  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
                    from templateflow import __version__ as _tf_verfrom . import apifrom . import apifrom . import apifrom . import api




  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
                from . import api    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layoutfrom .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout

from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>

  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout    
        install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)    install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>

install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)
install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
    install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
                return return_func(generator_func)(*args, **kwargs)return return_func(generator_func)(*args, **kwargs)return return_func(generator_func)(*args, **kwargs)
return return_func(generator_func)(*args, **kwargs)


  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
                results = list(results)results = list(results)results = list(results)results = list(results)



  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
                for r in _process_results(for r in _process_results(for r in _process_results(for r in _process_results(



  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
        for res in results:    for res in results:
for res in results:

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
      File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
for res in results:  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
    for r in destination_dataset.get(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
        for r in destination_dataset.get(    for r in destination_dataset.get(
for r in destination_dataset.get(

      File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
for r in destination_dataset.get(  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
        for r in _process_results(for r in _process_results(    

for r in _process_results(      File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results

for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
        for res in results:for res in results:
    
    for res in results:  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
for res in results:  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__


  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
    refds = require_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
        refds = require_dataset(refds = require_dataset(
    
    refds = require_dataset(  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
refds = require_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
    raise ValueError(u"No installed dataset found at "
ValueError: No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds001226_sub-PAT15/fmriprep_wf/single_subject_PAT15_wf/func_preproc_ses_preop_task_rest_wf/unwarp_wf/resample/sourcedata/templateflow.
        raise ValueError(u"No installed dataset found at "    raise ValueError(u"No installed dataset found at "
    raise ValueError(u"No installed dataset found at "

raise ValueError(u"No installed dataset found at "ValueError
: ValueErrorValueError: : ValueErrorNo installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds001226_sub-PAT15/fmriprep_wf/single_subject_PAT15_wf/func_preproc_ses_preop_task_rest_wf/unwarp_wf/resample/sourcedata/templateflow.: 
No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds001226_sub-PAT15/fmriprep_wf/single_subject_PAT15_wf/func_preproc_ses_preop_task_rest_wf/unwarp_wf/resample/sourcedata/templateflow.No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds001226_sub-PAT15/fmriprep_wf/single_subject_PAT15_wf/func_preproc_ses_preop_task_rest_wf/unwarp_wf/resample/sourcedata/templateflow.

No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds001226_sub-PAT15/fmriprep_wf/single_subject_PAT15_wf/func_preproc_ses_preop_task_rest_wf/unwarp_wf/resample/sourcedata/templateflow.
